const SPACING_TOKEN = {
  // Spacing token
  SPACING_XS: 4,
  SPACING_SM: 8,
  SPACING_MD: 16,
  SPACING_LG: 24,
  SPACING_XL: 32,
  SPACING_XXL: 40,
};

export const SPACING = {
  MARGIN_XS: SPACING_TOKEN.SPACING_XS, //4
  MARGIN_SM: SPACING_TOKEN.SPACING_SM, //8
  MARGIN_MD: SPACING_TOKEN.SPACING_MD, //16
  MARGIN_LG: SPACING_TOKEN.SPACING_LG, //24
  MARGIN_XL: SPACING_TOKEN.SPACING_XL, //32
  MARGIN_XXL: SPACING_TOKEN.SPACING_XXL, //40

  PADDING_XS: SPACING_TOKEN.SPACING_XS, //4
  PADDING_SM: SPACING_TOKEN.SPACING_SM, //8
  PADDING_MD: SPACING_TOKEN.SPACING_MD, //16
  PADDING_LG: SPACING_TOKEN.SPACING_LG, //24
  PADDING_XL: SPACING_TOKEN.SPACING_XL, //32
  PADDING_XXL: SPACING_TOKEN.SPACING_XXL, //40
};

export const ICON = {
  DEFAULT_SIZE: 24,
};
